### ISSUE TITLE
咨询H265播放技术

### ISSUE THREAD

**Issue by jeickey** [v354412101/wsPlayer#10]
我在用 zlm 推流，目前 H265 的解码播不出来， 
1. 用 websocket TS 流 播放 ws://<ip>:880/live/test.live.ts  是黑屏 ，用 http://<ip>:880/live/test.live.ts 在 vlc 里可以播放 (H265)  
2. 用 fmp4 的 url 播放 ws://192.168.5.43:880/live/v172.16.110.19-554-1-main.live.mp4  也是黑屏( H264的可以)  

请问咱们这个库升级到 H265 版本了嘛，盼回，

**Comment by tokamakz** [comment]
你好，
1、[README.md](https://github.com/v354412101/wsPlayer/blob/master/README.md)中已经说明，wsplayer只支持ws-mp4播放，不支持ws-ts播放；
2、目前v1版本只支持ws-mp4  H264码流播放，不支持H265播放；v2版本计划支持H265，我在debug环境已经开发好了，但是还有很多异常case需要完善，上线时间待定；

**Comment by tokamakz** [comment]
chrome 107+ 已经支持H265硬解了，而且wsplayer可以无需修改任何代码，原生支持。
