### ISSUE TITLE
fmp4爆音问题

### ISSUE THREAD

**Issue by lystormenvoy** [v354412101/wsPlayer#11]
测试页： http://183.62.8.181:9487/wsfmp4/index.html
同一个推流转出的HLS流： http://183.62.8.181:9487/wsfmp4/livehls.html

wsPlayer播放ws-fmp4时会有频繁的爆音，移动端几乎百分百会比较严重。桌面端随着刷新有时频率没那么高，有时频率很高。
同一个推流到ZLM转出的hls流播放则正常

**Comment by tokamakz** [comment]
请确认是否是aac音频格式

**Comment by lystormenvoy** [comment]
> 请确认是否是aac音频格式

确认是aac的，就是普通的rtmp推流。h264+aac。

**Comment by EssLi** [comment]
确实有爆音问题

**Comment by lystormenvoy** [comment]
> 确实有爆音问题

@tokamakz

**Comment by EssLi** [comment]
我发现可能和源有关系，起码我不再觉得是播放端问题了
