### ISSUE TITLE
vue项目中使用延迟卡帧问题

### ISSUE THREAD

**Issue by lk-yu** [v354412101/wsPlayer#13]
您好，请问使用vue项目中，本地开发视频流是正常的，再部署到线上的时候，视频就又很高的延迟卡帧了

**Comment by laogaochg** [comment]
感觉要视频追帧，你后来怎么解决？

**Comment by tokamakz** [comment]
可能是网络问题，后续wsplayer考虑增加console功能，用来查看码率，帧率，卡顿日志这些信息。
