### ISSUE TITLE
使用的ws链接中包含有音频数据，会提示错误

### ISSUE THREAD

**Issue by niehuaihua** [v354412101/wsPlayer#14]
使用[ZLMediaKit]推出来的ws链接，用wsPlayer播放的时候出现Uncaught DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.4d4028, alaw"') is unsupported错误提示，后来我把音频给禁了，就能正常显示
![H0`UD`9{6F7KV4~_$34HW@0](https://user-images.githubusercontent.com/48516422/200993170-5344f22a-f275-408d-9dcc-38972fdd4c7b.jpg)

**Comment by Forfires** [comment]
chrome不支持g711-a 的音频编码，只能把音频丢掉把视频推给MSE，当然也可以把摄像机的音频换为aac

**Comment by MasterShi** [comment]
说来也怪，如果走 http而不是ws， 直接video标签就能播放了， 应该是同一个音视频编码吧

**Comment by tokamakz** [comment]
浏览器不支持alaw这种音频编码格式。
