### ISSUE TITLE
搭配zlm播放ws+fmp4感觉有点卡顿

### ISSUE THREAD

**Issue by zhouxiaojun2008** [v354412101/wsPlayer#15]
zlm出来的同一路流
1 ffplay播放 http+fmp4 看起来流畅，至少视频画面的秒数是一秒一秒的显示
2 wsPlayer.js播放感觉有卡顿，观察画面的是时间戳看到画面有跳秒，比如从15s到了17s，很容易观察到，并且一致持续
  前端js代码我大概看了一下，发现是不是在onupdateend函数处理有一些问题？
3 因为视频源是我推给zlm的，也不排除是我的时间戳设置存在问题，但对比ffplay来看，wsPlayer.js表现没有ffplay好。

大佬有空指导一下么，js我不太会玩转？随时可提供在线环境调试js

**Comment by v354412101** [comment]
zlm需要开启时间戳平滑处理

看你的github名字，我好像认识你，把你联系方式告诉我，或者你叫我qq：354412101

**Comment by real23355** [comment]
hi,我最近也在调试这个，也有同样的情况。不知道你有解决么？

**Comment by Greasen** [comment]
确实跳帧比较严重，而且多画面长时间播放下，容易延迟过高，崩溃。

**Comment by tokamakz** [comment]
主要是zlm分发的fmp4的时间戳需要时平滑的。请确认https://github.com/ZLMediaKit/ZLMediaKit/blob/d4f80171171cdfc00c6be27fab33124eae6a1bdd/src/Record/MP4Muxer.cpp#L113
这个是开启的
