### ISSUE TITLE
支持音频吗？我播放没有声音

### ISSUE THREAD

**Issue by wahjrzd** [v354412101/wsPlayer#16]
这个地址https://www.onlinemp4parser.com/  有声音，音频格式是aac的 ，播放也没看到报错

**Comment by tokamakz** [comment]
支持音频，比如aac。
但是demo中，默认将video标签设置为muted了，所有没有声音。
https://github.com/v354412101/wsPlayer/blob/f4eed07d31bcef17fc5e0c0673723774781becee/index.html#LL7C12-L7C17
