### ISSUE TITLE
rtsp视频流播放不出来

### ISSUE THREAD

**Issue by Crayon-kk** [v354412101/wsPlayer#4]
流不断在传输，但是页面不显示播放器
![image](https://user-images.githubusercontent.com/33805801/141743673-44d11016-a530-4769-9e65-aece5bd6b5a0.png)

![image](https://user-images.githubusercontent.com/33805801/141743590-1bc09546-7ec2-4e78-9ff9-a3caa1d79edd.png)

**Comment by tokamakz** [comment]
我修复了，你重新拉代码，试试？

**Comment by Crayon-kk** [comment]
好的
