### ISSUE TITLE
从zlm服务器拉流播放会卡顿

### ISSUE THREAD

**Issue by xxxxxxbin6** [v354412101/wsPlayer#5]

**Comment by tokamakz** [comment]
请提供更具体的问题现象的描述，以便定位问题的原因。
比如从ZLM拉流，用VLC，ffplay标准播放器播放也会卡顿吗？
只是卡顿一下，还是一直卡？

**Comment by xxxxxxbin6** [comment]
用ffplay或者其他播放器不会卡,但是用wsPlayer播放会卡,是一直卡,而且还会回帧

**Comment by tokamakz** [comment]
回帧，可能是视频里面有B帧导致的。
方便的话 ，你可否把视频源录一段给我，我在我的环境复现一下
QQ：354412101
