### ISSUE TITLE
播放时间越长，wsPlayer播放延时越大

### ISSUE THREAD

**Issue by tokamakz** [v354412101/wsPlayer#6]
![example](https://user-images.githubusercontent.com/9720127/164886234-93753171-3ea9-4e23-ac3d-9eebd41f8c9f.jpg)

问题的现象：vlc和wsPlayer都从ZLM拉流播放，播放一段时间后，vlc播放的画面无延迟，但wsPlayer播放延迟变大，并且随着播放时间越长，延迟也会变大

**Comment by lisicn** [comment]
延迟问题同样存在。
刷新页面后的延迟
![1](https://user-images.githubusercontent.com/38556416/180106066-472b0374-13c8-4cdd-a694-7c76f7bf4cc0.png)
长时间播放的延迟
![2](https://user-images.githubusercontent.com/38556416/180106070-c46d0851-fc89-41c1-8272-3b636b85aa1a.png)

**Comment by Greasen** [comment]
我也出现了这样的情况，使用 FFplayer 播放无延迟，但是用wsplayer 长时间的播放下会产生延迟，播放时间越长，延迟也会变大。

**Comment by Greasen** [comment]
> 

尤其是在多个播放器同时播放的情况下。
